
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 955245973648-ckh0oq2nvl7g116h761ug23fvn2st6u4.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 694065238287400
            client-secret: 33066fe89eef03b9d34fc9f5c27f113f
            scope:
              - email
              - public_profile
          naver:
            client-id: _oN6rbgdKbr_Yctj29Og
            client-secret: bOdZRByKkW
            scope:
              - name
              - email
            client-name: naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  redis:
    host: localhost
    port: 6379
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        discriminator:
          ignore_explicit_for_joined: false
        hbm2ddl:
          auto: create-drop


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jwt:
    secret-key: hiberna- te
    access-token-invalid-hour: 720
    refresh-token-invalid-hour: 720
    blacklist:
      access-token: logout
  jackson:
    serialization:
      fail-on-empty-beans: false
      write-dates-as-timestamps: false

logging:
  level:
    org.hibernate.SQL: debug
    level:
      com:
        amazonaws:
          util:
            EC2MetadataUtils: error
cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: AKIAUYJVJZYSWOH7WJOF
      secret-key: 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
    s3:
      file-bucket: i-solution-file-bucket
      img-bucket: i-solution-img-bucket


qr:
  secret-key: is!Qr-key-test
  expiration-minute: 60 # ????? 2??? ??!